name: Build, test and deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node Dependencies
        run: npm i

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/pest

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ vars.HOST }}
          REMOTE_USER: ${{ vars.USERNAME }}
          REMOTE_PORT: 10229
          TARGET: ${{ vars.TARGET }}
          EXCLUDE: "/node_modules/, /.idea/, /.git/, /vendor/, /.github/, /.agents/, /.claude/"
        with:
          REMOTE_HOST: ${{ vars.HOST }}
          REMOTE_USER: ${{ vars.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}

      - name: Composer and migrations
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ vars.USER }}@${{ vars.HOST }}:10229
          privateKey: ${{ secrets.KEY }}
          command: |
            cd ${{ vars.TARGET }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan env:decrypt --env=production --key=${{ secrets.ENCRYPT_KEY }} --force --filename=.env
            php artisan cache:clear
            php artisan view:cache
            php artisan config:cache
            php artisan storage:link
